### ISSUE TITLE
Choose type of gene ID

### ISSUE THREAD

**Issue by slowkow** [endrebak/kg#1]
Thanks for the great package! It just works, and I'm very impressed with the effective use of joblib and other packages. I could definitely learn a few things about making Python packages from your code.

However, I'd like to ask if you could support several gene identifiers like Entrez ID or Ensembl. The command below outputs gene symbols, but it is not clear to me if these gene symbols are HGNC names or some other names. Could you please clarify? Could you add an option to output other types of identifiers?

```
kg --mergecol=0 --noheader --genes --definition --species=hsa <(echo 01200)
```

```
Cache path is: /Users/slowikow/.kegg/ (Time:  Thu, 29 Oct 2015 10:10:24 )
Get KEGG gene to external gene map. (Time:  Thu, 29 Oct 2015 10:10:24 )
Get KEGG path to gene map. (Time:  Thu, 29 Oct 2015 10:10:25 )
Get KEGG pathway to definition map. (Time:  Thu, 29 Oct 2015 10:10:25 )
Connect KEGG gene map and KEGG pathway map. (Time:  Thu, 29 Oct 2015 10:10:26 )
/Users/slowikow/anaconda/lib/python2.7/site-packages/ebs/merge_cols.py:74: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  in_df = in_df.sort(pre_merge_sort_order_col)
Attaching pathway definitions. (Time:  Thu, 29 Oct 2015 10:10:26 )
01200   ME3     Carbon metabolism
01200   PGAMA   Carbon metabolism
01200   PGAM-B  Carbon metabolism
01200   HEL-S-35        Carbon metabolism
01200   PGAM1   Carbon metabolism
01200   PFKF    Carbon metabolism
```

**Comment by endrebak** [comment]
Thanks for reporting. Will look at it now.

Ps. there was a bug in an early version, is your version `0.0.5`?  I haven't included version info yet, so you should just try `pip install kg==0.0.5`.

**Comment by endrebak** [comment]
I try to use the gene ids called `external_gene_name`, because they seem like the most common ones.

```shell
pip install biomartian==0.0.18
biomartian -d hsap -i external_gene_name -o entrezgene | grep ME3
10873.0	ME3
10197.0	PSME3
4832.0	NME3
```

I am trying to keep this library minimal, only the stuff you can't do anywhere else. This is to avoid duplication, but also the `rest/KEGG` I use only has funding til 2016 sometime, IIRC, so I might have to rewrite the code then. 

Most conversions can be done in `biomartian`, like shown above. Ps. the `.0` are a bug I'll get around to fixing; entrez_ids are ints.

You are right that lots of info is lacking though. I'll update the docs, and please tell me if you see something you'd want added.

Also feel free to suggest other sources for kegg conversions and I'll add them to the README. If there are better ways of getting KEGG data, I'd like to know and let others know.

**Comment by endrebak** [comment]
Since common gene names are ambiguous, I'll try to add support for a different format.

(I should also check if there is a common gene name to common gene name map in biomart though. Would help resolve ambiguity.)

**Comment by endrebak** [comment]
Now uses entrezgene by default.

Thanks for making me aware of this problem.

Feel free to reopen for any reason at all.
